### ISSUE TITLE
Broken URLs for content block editing

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#170]
This is in Zikula 1.4.3 build 129.

Try to edit an existing content block within a page.  Click on the -> arrow icon and select Edit, which leads to:

http://localhost/zcs1/?module=content&type=admin&func=editcontent&cid=%7BcommandArgument%7D

and an error "Error! Unknown content-ID".

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/pull/3006

**Comment by robbrandt** [comment]
This is still a problem.
Note that the URL I posted is literal:
"http://localhost/zcs1/?module=content&type=admin&func=editcontent&cid=%7BcommandArgument%7D"
which translates to cid={commandArgument}.  The curly braces are really in the URL.

**Comment by robbrandt** [comment]
If you saw my last comment, ignore it.  I was testing the wrong instance of Zikula.

However there's a problem with routing that didn't exist before this fix.  I cannot actually access Content administration.  http://localhost/zcs2/index.php?module=content&type=admin&func=index actually routes me to the home page. It seems that http://localhost/zcs2/index.php?module=Content&type=admin&func=index (with the first letter of content in caps) does work, but those aren't the links provided by the module.

Interestingly, the page title says "Page list and content struction" but the page that renders is the home page.

**Comment by Guite** [comment]
Can't reproduce this one. For me even both `Content` and `content` work. Even played with different short url settings and start page options. `http://localhost/src/?module=content&type=admin&func=index` always works like a charm :confused:  Please recheck and if the problem persists please create a new issue for it.
